language: node_js
node_js:
    - 0.8
install:
    - sh init.sh
script:
    - npm test
    - node gear build &
    - cd build
    - node test-server.js
notifications:
    email:
        - akshar@akshar.co.in
