language: node_js
node_js:
    - 0.8
install:
    - sh init.sh
script:
    - npm test
    - node gear build migrate
    - cd build
    - node gear build test
services:
  - couchdb
notifications:
    email:
        - akshar@akshar.co.in
